# Generated by Django 5.2.1 on 2025-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('beklemede', 'beklemede'), ('tamamlandi', 'tamamlandi'), ('iptal', 'iptal')], default='beklemede', max_length=10),
        ),
    ]
