# Generated by Django 5.2.1 on 2025-05-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_payment_status_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
    ]
