# Generated by Django 5.2.1 on 2025-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_status_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
