# Generated by Django 5.2.1 on 2025-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250611_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Kiraci'), ('owner', 'Ev Sahibi'), ('admin', 'Admin')], default='tenant', max_length=20),
        ),
    ]
