# Generated by Django 5.2.1 on 2025-05-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinyhouse',
            name='tenant',
        ),
    ]
