# Generated by Django 5.2.1 on 2025-05-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_tinyhouse_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinyhouse',
            old_name='status',
            new_name='tiny_house_status',
        ),
    ]
