# Generated by Django 5.2.1 on 2025-05-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_rename_status_tinyhouse_tiny_house_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_status', models.CharField(choices=[('beklemede', 'beklemede'), ('onaylı', 'onaylı'), ('iptal', 'iptal')], default='beklemede', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tiny_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.tinyhouse')),
            ],
        ),
    ]
