# Generated by Django 5.2.1 on 2025-05-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_amount',
        ),
    ]
