# Generated by Django 5.2.1 on 2025-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('beklemede', 'beklemede'), ('onayli', 'onayli'), ('iptal', 'iptal')], default='beklemede', max_length=10),
        ),
    ]
