# Generated by Django 5.2.1 on 2025-06-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_reservation_status'),
    ]

    operations = [
         migrations.RunSQL(
        open('reservations/sql/procedures.sql', encoding='utf-8').read()
         )
    ]
