# Generated by Django 5.2.1 on 2025-06-12 20:31

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_merge_20250612_2013'),
    ]

    operations = [
        migrations.RunSQL(
            # يقرأ ملف procedures.sql بعد تعديله بأسماء الجداول الصحيحة
            open('reservations/sql/procedures.sql', encoding='utf-8').read()
        ),
    ]
